apiVersion: apps/v1 #
kind: Deployment #
metadata: #
  name: webapp-deployment #
  labels: #
    app: webapp #
spec: #
  replicas: 1 #
  selector: #
    matchLabels: #
      app: webapp #
  template: #
    metadata: #
      labels: #
        app: webapp #
    spec: #
      containers: #
      - name: webapp #
        image: zezl7/esd-2024-kubernetes:latest #
        ports: #
        - containerPort: 3000 #
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    name: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100